- name: Assert Required variables
  assert:
    that:
      - local_user is defined
      - new_hash is defined

- name: Check if user account exists
  raw: "id {{ local_user }}"
  register: user_check
  ignore_errors: true
  changed_when: false

- assert:
    that:
      - "'uid=' in user_check.stdout"
    fail_msg: "User account '{{ local_user }}' does not exist."
    success_msg: "User account '{{ local_user }}' exists."

# - name: Set new user hash
#   lineinfile:
#     path: "/etc/shadow"
#     regexp: "^{{local_user}}:"
#     line: "root:{{ hostvars['localhost']['new_hash'] }}:{{days_since_epoch}}:0:99999:7:::"
#     validate: "grep -F '{{ hostvars['localhost']['new_hash'] }}' %s"
#     backup: true
#   register: newhash
  
- name: Change User Password
  user:
    name: "{{ local_user }}"
    update_password: always
    password: "{{ new_hash }}"
  register: newhash
  no_log: true